globalThis.vectorObserve=()=>{
 const visible=el=>!!(el.getClientRects().length)&&getComputedStyle(el).visibility!=='hidden';
 if(Array.from(document.querySelectorAll('input[type=password],input[autocomplete=one-time-code],input[aria-label="PIN"]')).some(visible))throw Error('Finish Facebook sign-in or restore your Messenger history in Chrome.');
 const label=el=>(el.getAttribute('aria-label')||el.getAttribute('placeholder')||el.innerText||el.getAttribute('alt')||el.getAttribute('title')||el.name||el.tagName).trim().slice(0,220);
 const inboxRow=el=>{const lines=(el.innerText||'').split('\n').map(s=>s.trim()).filter(Boolean);return location.pathname.startsWith('/marketplace/inbox')&&el.tagName==='DIV'&&el.getAttribute('role')==='button'&&!!el.closest('main,[role="main"]')&&!el.closest('[role="dialog"],[role="log"],[contenteditable="true"]')&&!el.querySelector('button,a,input,[role="button"],[contenteditable="true"]')&&lines.length>=3&&lines[1].startsWith('· ')};
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT,{acceptNode:n=>{const el=n.nodeType===1?n:n.parentElement;if(!el||!visible(el)||el.closest('script,style,input,textarea,[contenteditable="true"]'))return NodeFilter.FILTER_REJECT;return n.nodeType===3||(n.nodeType===1&&n.matches('img,[role="img"]'))?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_SKIP}});let textParts=[],current;while((current=walker.nextNode())){const value=current.nodeType===1?(current.getAttribute('aria-label')||current.getAttribute('alt')||current.getAttribute('title')||'').trim():current.textContent.trim();if(value)textParts.push(current.nodeType===1?'[Image: '+value+']':value)}
 const standardControls=Array.from(document.querySelectorAll('a,button,input,textarea,select,[role="button"],[role="tab"],[role="combobox"],[role="option"],[role="menuitem"],[role="menuitemradio"],[role="radio"],[contenteditable="true"]'));
 // Facebook sometimes renders this navigation command as plain menu text.
 // Expose only the exact leaf label so the agent can use the normal guarded
 // click path instead of repeatedly searching or guessing coordinates.
 const semanticControls=Array.from(document.querySelectorAll('div,span')).filter(el=>{const text=el.innerText?.trim()||'';return visible(el)&&/^(?:Open in Messenger|Chat settings|Conversation details)$/i.test(text)&&!Array.from(el.children).some(child=>child.innerText?.trim()===text)});
 const controls=[...new Set([...standardControls,...semanticControls])].filter(visible).slice(0,300);
 const inboxRows=controls.filter(inboxRow).map(el=>{const lines=(el.innerText||'').split('\n').map(s=>s.trim()).filter(Boolean),anchor=el.closest('a[href*="/messages/t/"]'),url=anchor?.href;return {label:label(el),person:lines[0]||'',listing:(lines[1]||'').replace(/^·\s*/,''),preview:lines[2]||'',...(url?{url}:{})}}).filter(r=>r.person&&r.listing);
 globalThis.vectorElements=[];const nodes=controls.map((el,id)=>{globalThis.vectorElements[id]=el;return {id,kind:inboxRow(el)?'inbox-conversation':'control',tag:el.tagName,role:el.getAttribute('role')||'',selected:el.getAttribute('aria-selected'),label:label(el),type:el.type||'',href:el.href||'',value:el.type==='password'||el.autocomplete==='one-time-code'||/security code|verification code/i.test(label(el))?'':el.value||'',options:el.tagName==='SELECT'?Array.from(el.options).map(o=>({value:o.value,text:o.text})):[]}});
 const listings=Array.from(document.querySelectorAll('a[href*="/marketplace/item/"]')).filter(visible).map(el=>({url:el.href.split('?')[0],text:(el.innerText||el.getAttribute('aria-label')||'').slice(0,1500),image:el.querySelector('img')?.currentSrc||el.querySelector('img')?.src||''}));
 // Loading indicators often have accessible names but no text nodes. Preserve
 // them separately so an unchanged document is not mistaken for a finished list.
 const content=document.querySelector('main,[role="main"]')||document.body;
 const loading=Array.from(content.querySelectorAll('[role="progressbar"],[aria-busy="true"],[aria-label],[role="status"]')).filter(visible).filter(el=>el.getAttribute('role')==='progressbar'||el.getAttribute('aria-busy')==='true'||/^loading(?:\b|[.…])/i.test(label(el))).map(el=>label(el)).slice(0,20);
 return {url:location.href,title:document.title,text:textParts.join('\n').slice(-24000),nodes,listings,inboxRows,loading,visibility:document.visibilityState};
};
