const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const d=new JSDOM('<div role="grid" aria-label="Marketplace"><div role="row"><a href="/messages/t/101/" aria-label="Group chat: Alex · Oak chair">row</a></div></div><div role="grid" aria-label="Chats"><a href="/messages/t/999/">Personal chat</a></div>',{url:'https://www.facebook.com/messages/t/101/',runScripts:'outside-only'});
for(const el of d.window.document.querySelectorAll('*')){el.getClientRects=()=>[{}];el.innerText=el.textContent}
d.window.document.querySelector('a').innerText='Alex · Oak chair\nUnread message:\nAlex: $80 firm\n · \n1m';
d.window.eval(fs.readFileSync(__dirname+'/../Extension/observer.js','utf8'));
const observed=JSON.parse(JSON.stringify(d.window.vectorObserve()));
assert.equal(observed.inboxRows.length,1,'personal conversations are excluded');
assert.deepEqual(observed.inboxRows[0],{label:'Group chat: Alex · Oak chair',person:'Alex',listing:'Oak chair',preview:'Alex: $80 firm',url:'https://www.facebook.com/messages/t/101/'});
assert.equal(observed.nodes.filter(n=>n.kind==='inbox-conversation').length,1);
d.window.close();
let page='broken',folder=false,queue=[];
const item={id:1,view:'Buying',name:'Oak chair',url:'https://www.facebook.com/marketplace/item/1/'},work={enabled:true,leads:[{id:'Alex',url:'https://www.facebook.com/messages/t/101/'}],conversationProgress:{candidates:[],reads:{},censusComplete:false}},state={jobs:[],inboxFingerprintVersionBuying:2};
const c=vm.createContext({Date,Map,Set,String,JSON,Error,Array,Object,rows:[item],nativeState:state,monitoringWanted:()=>true,workFor:()=>work,validThreadURL:u=>/^https:\/\/www\.facebook\.com\/messages\/t\/\d+\/?$/.test(u||''),marketplaceID:u=>u?.match(/item\/(\d+)/)?.[1],delay:async()=>{},saveSoon(){},queueJob:(kind,r,extra)=>queue.push({kind,...extra}),nativeCall:async(method,args)=>{
 if(method==='browserAction'){if(args.action==='scroll'&&args.value==='up')return {scrolled:false,after:0};if(args.action==='navigate')page=args.url.includes('/marketplace/inbox')?'broken':'messenger';if(args.action==='click')folder=true;return{}}
 if(page==='broken')return {url:'https://www.facebook.com/marketplace/inbox?targetTab=BUYER',inboxRows:[],text:'Sorry, something went wrong.'};
 return folder?observed:{url:'https://www.facebook.com/messages/t/101/',inboxRows:[],nodes:[{id:7,role:'button',label:'Marketplace 2 new messages'}],epoch:1};
}});
vm.runInContext(fs.readFileSync(__dirname+'/../Web/conversations.js','utf8'),c);
(async()=>{const job={kind:'poll',side:'Buying'};await c.pollInbox(job);assert.match(job.completionNote,/via Messenger.*1 matched.*1 changed/);assert.equal(queue.length,1);assert.equal(queue[0].kind,'sync');assert.equal(work.conversationProgress.candidates[0].url,'https://www.facebook.com/messages/t/101/');queue=[];await c.pollInbox({kind:'poll',side:'Buying'});assert.equal(queue.length,0,'unchanged fallback previews do not repeatedly queue AI');observed.inboxRows[0].url='https://www.facebook.com/messages/t/202/';observed.inboxRows[0].person='Other';observed.inboxRows[0].listing='Other item';let scrolled=0;const base=c.nativeCall;c.nativeCall=async(method,args)=>{if(method==='browserAction'&&args.action==='scroll'&&args.value!=='up'){scrolled++;observed.inboxRows=[{person:'Alex',listing:'Oak chair',url:'https://www.facebook.com/messages/t/101/'}];return{scrolled:true}}return base(method,args)};const older=await c.fallbackMessengerInbox([item],'Alex');assert.equal(scrolled,1);assert(older.inboxRows.some(x=>x.person==='Alex'),'older seller lookup scrolls locally to the requested identity');observed.inboxRows=[{person:'Other',listing:'Other item',url:'https://www.facebook.com/messages/t/202/'}];scrolled=0;c.nativeCall=async(method,args)=>{if(method==='browserAction'&&args.action==='scroll'&&args.value!=='up'){scrolled++;if(scrolled===3)observed.inboxRows=[{person:'Alex',listing:'Oak chair',url:'https://www.facebook.com/messages/t/101/'}];return{scrolled:false,atEnd:true}}return base(method,args)};const delayed=await c.fallbackMessengerInbox([item],'Alex');assert.equal(scrolled,3);assert(delayed.inboxRows.some(x=>x.person==='Alex'),'a temporary list end waits for asynchronously loaded conversations');
 let topChecks=0;observed.inboxRows=[{person:'Older',listing:'Oak chair',url:'https://www.facebook.com/messages/t/303/'}];c.nativeCall=async(method,args)=>{if(method==='browserAction'&&args.action==='scroll'&&args.value==='up'){topChecks++;if(topChecks===2)observed.inboxRows=[{person:'Newest',listing:'Oak chair',url:'https://www.facebook.com/messages/t/404/'}];return{scrolled:true,after:topChecks===2?0:100}}return base(method,args)};const newest=await c.fallbackMessengerInbox([item]);assert.equal(topChecks,2);assert.equal(newest.inboxRows[0].person,'Newest','polling starts at newest messages after a deep history scan');c.nativeCall=async(method,args)=>method==='browserAction'&&args.action==='scroll'?{scrolled:false,after:100}:base(method,args);await assert.rejects(c.fallbackMessengerInbox([item]),/newest Marketplace conversations could not be reached/);
 console.log('PASS Messenger fallback extracts scoped previews and resumes change detection without AI');})().catch(e=>{console.error(e);process.exitCode=1});
