const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../Web/native.js','utf8');
const url='https://www.facebook.com/marketplace/item/123/',page='https://www.facebook.com/marketplace/you/selling/';
async function scenario(commit,href,fail=false,repeats=1,action='click'){
const calls=[],job={};let n=0;
const c=vm.createContext({Date,Map,JSON,Error,stopGeneration:0,itemRevision:()=>0,jobAllowed:()=>true,actionSchema:{},settings:false,saveSoon(){},signalCore(){},delay:async()=>{},validListingURL:u=>u===url,nativeCall:async(method,args)=>{if(method==='observe')return {url:page,nodes:[{id:7,label:'Camera Posted 3 weeks ago',href}],listings:[],epoch:1};calls.push(args);if(fail)throw Error('Blocked control');return {}},infer:async()=>n++>=repeats?{action:'done',result:'{}',note:''}:{action,id:7,url:'',note:'Inspect listing'}});
vm.runInContext(source.slice(source.indexOf('async function browserAgent('),source.indexOf('async function executeJob(')),c);if(fail){await assert.rejects(c.browserAgent(job,'Read listing',{commit}),/Blocked control/)}else await c.browserAgent(job,'Read listing',{commit});return {calls,job};
}
(async()=>{let r=await scenario(false,url);assert.equal(r.calls[0].action,'navigate');assert.equal(r.calls[0].url,url);const empty=await scenario(false,url,false,1,'navigate');assert.equal(empty.calls[0].url,url,'empty navigation resolves only the selected observed listing');assert.equal(r.calls[0].allowCommit,false);assert.equal(r.job.browserActions[0].state,'completed');r=await scenario(false,'');assert.equal(r.calls[0].action,'click');assert.equal(r.calls[0].allowCommit,false);r=await scenario(true,url);assert.equal(r.calls[0].action,'click');r=await scenario(false,'',true);assert.equal(r.job.browserActions[0].state,'failed');assert.equal(r.job.browserActions[0].error,'Blocked control');r=await scenario(false,'',false,4);assert.equal(r.calls.length,2,'ineffective clicks stop after two attempts');console.log('PASS read-only observed listing links use navigation; other controls retain guard; actions recorded');})().catch(e=>{console.error(e);process.exitCode=1});
