const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const native=fs.readFileSync(__dirname+'/../Web/native.js','utf8'),conversations=fs.readFileSync(__dirname+'/../Web/conversations.js','utf8');
const jobs=Array.from({length:700},(_,i)=>({id:'old-'+i,kind:'poll',itemId:null,state:'done',created:i}));jobs[3].kind='scan';jobs[3].state='running';
const c=vm.createContext({crypto,nativeState:{jobs,importReview:{jobId:'old-1'}},render(){},saveSoon(){},saveRoutineSoon(){},addActivity(){}});
for(const name of ['compactJobs','queueJob','retryableJob'])vm.runInContext(native.split('\n').find(l=>l.startsWith('function '+name+'(')),c);
const queued=c.queueJob('poll');
assert(queued&&queued.state==='queued');
assert.equal(queued.routineOnly,true,'routine polls begin with batched persistence');
assert(c.nativeState.jobs.length<=453,'completed job history remains bounded');
assert(c.nativeState.jobs.some(j=>j.id==='old-1'),'active import review job is retained');
assert(c.nativeState.jobs.some(j=>j.id==='old-3'),'running job is retained');
assert(c.nativeState.jobs.includes(queued),'new work is retained');
assert(c.nativeState.jobs.filter(j=>j.kind==='poll'&&j.state==='done'&&j.id!=='old-1').length<=5,'completed polling history remains compact');
const stale={id:'stale',kind:'sync',itemId:1,state:'needs_you',created:1,note:'Old problem'},latest={id:'latest',kind:'sync',itemId:1,state:'needs_you',created:2,note:'Current problem'},stopped={id:'stopped',kind:'price',itemId:1,state:'needs_you',created:3,note:'Stopped. Review first.'};c.nativeState.jobs.push(stale,latest,stopped);assert.equal(c.retryableJob(stale),false,'superseded failures cannot be retried');assert.equal(c.retryableJob(latest),true,'latest actionable failure can be retried');assert.equal(c.retryableJob(stopped),false,'deliberately stopped work cannot be retried blindly');
vm.runInContext(conversations.split('\n').find(l=>l.startsWith('function compactConversationText(')),c);
const needle='LATEST BUYER MESSAGE',text='a'.repeat(9000)+needle+'b'.repeat(9000),compact=c.compactConversationText(text,needle);
assert(compact.length<=6000);
assert(compact.includes(needle),'stored evidence retains the exact latest message');
assert.equal(c.compactConversationText('short',needle),'short');
console.log('PASS completed jobs and stored conversation evidence stay bounded without losing active work or latest-message proof');
