// Status is derived from saved jobs and listing evidence, never from an AI toggle.
const taskNames={price:'Pricing research',sync:'Checking messages',poll:'Checking inbox',draft:'Preparing listing',publish:'Publishing',reply:'Replying',manual:'Sending reply',offer:'Negotiating purchase',scan:'Finding listings',import:'Finding your listings'};
function actionableJobIssue(j){return ['failed','needs_you'].includes(j?.state)&&!/^Stopped\.|^Work paused\./i.test(j.note||'')}
function jobScopeKey(j){return j.kind+(['reply','manual'].includes(j.kind)?':'+(j.leadURL||'unknown'):'')}
function latestItemJobs(r){const jobs=new Map();for(const j of nativeState.jobs.filter(j=>j.itemId===r.id))jobs.set(jobScopeKey(j),j);return [...jobs.values()]}
function listingLabel(r){return r.view==='Sold'?'Sold':r.liveURL?'Live':jobFor(r,'publish')?'Not live · Publishing':r.view==='Selling'?'Not live · Draft':'Not live'}
function automationLabel(r){const jobs=latestItemJobs(r),active=jobs.find(j=>j.state==='running');if(active)return taskNames[active.kind]||active.kind;const failed=jobs.find(actionableJobIssue);if(failed)return 'Needs attention';const queued=jobs.find(j=>j.state==='queued');if(queued)return !nativeState.connected?'Waiting for AI connection':!jobAllowed(queued)?'Paused · '+(taskNames[queued.kind]||queued.kind):'Queued · '+(taskNames[queued.kind]||queued.kind);const w=workFor(r);if(!laneEnabled[r.view])return 'Paused';if(!w.enabled)return monitoringWanted(r)?(nativeState.connected?'Monitoring · Replies off':'Waiting for AI connection'):'Off';if(w.needs)return 'Needs attention';return w.leads.some(l=>l.state==='Negotiating')?'Negotiating':'Monitoring messages'}
function buyingCardIssue(r){if(r.view!=='Buying'||automationLabel(r)!=='Needs attention')return null;const job=latestItemJobs(r).find(actionableJobIssue),note=job?.note||workFor(r).last||'This deal needs your review.',distance=note.match(/^Pickup is ([\d.]+) km\. Review this deal before replying\.$/i);if(distance)return {type:'distance',title:'Pickup distance needs review',detail:'Pickup is '+distance[1]+' km from your starting point, beyond your '+radius+' km limit.',next:'Continue this deal, pass on it, or change your distance limit.'};return {type:'task',title:(job?taskNames[job.kind]||'Automation':'Automation')+' needs review',detail:note,next:workFor(r).next||'Review the task before continuing.'}}
function sellingStatus(r){const w=workFor(r),latest=latestItemJobs(r),active=latest.find(j=>j.state==='running'),messageIssues=latest.filter(j=>['sync','reply','manual'].includes(j.kind)&&actionableJobIssue(j));return {monitor:!laneEnabled.Selling?'Paused':w.monitorPaused?'Off':'On',replies:!laneEnabled.Selling?'Paused':w.enabled?'On':'Off',action:active?taskNames[active.kind]||'Working':'',messageIssue:messageIssues.length>0,messageIssueCount:messageIssues.length}}
function restrictedItems(){const found=new Map();for(const x of nativeState.restrictedListings||[])found.set(importEvidenceText(x.name),x);for(const j of nativeState.jobs.filter(j=>j.kind==='import'))for(const x of j.importProgress?.excluded||[])found.set(importEvidenceText(x.name),x);for(const x of nativeState.importReview?.excluded||[])found.set(importEvidenceText(x.name),x);return [...found.values()]}
function attentionItems(){const result=[];for(const r of rows.filter(r=>r.stockTracked&&r.view!=='Sold')){const jobs=latestItemJobs(r),issues=[];if(!photos[r.photo])issues.push({title:'Needs photo',detail:r.liveURL?'No photo is saved in Vector. Add an original photo for future listing work.':'Add an original product photo before this item can be published.',action:'Add photo',edit:true});if(!r.liveURL&&r.policy!=='store'){const missing=invMissing(r).filter(x=>x!=='photo'&&!(['asking price','minimum price'].includes(x)&&jobs.some(j=>j.kind==='price'&&['queued','running'].includes(j.state))));if(missing.length)issues.push({title:'Missing details',detail:'Add '+missing.join(', ')+'.',action:'Edit item',edit:true});}for(const j of jobs.filter(actionableJobIssue)){const duplicate=/duplicat|already used|same (?:photo|image)/i.test(j.note||'')&&/photo|image/i.test(j.note||'');issues.push({title:duplicate?'Photo rejected':(taskNames[j.kind]||j.kind)+' needs attention',detail:duplicate?'Marketplace reported a reused or duplicate image. Add a new original product photo, then review publication before retrying.':'Task stopped. Review the error before retrying.',evidence:j.note||'',action:duplicate?'Replace photo':'Review task',edit:duplicate,job:j});}if(issues.length)result.push({r,name:r.name,issues});}for(const x of restrictedItems())result.push({name:x.name,restricted:true,issues:[{title:'Facebook listing restriction',detail:x.quote,next:'Facebook requires you to review this listing. Vector did not treat it as live, and the rest of your automation can continue.',action:'Review on Facebook'}]});return result}
function attentionIssueCount(){const items=attentionItems(),staticIssues=items.reduce((n,x)=>n+x.issues.filter(i=>!i.job).length,0),jobIssues=items.reduce((n,x)=>n+x.issues.filter(i=>i.job).length,0),orphanJobs=blockerGroups().reduce((n,g)=>n+g.jobs.filter(j=>!rows.some(r=>r.id===j.itemId&&r.stockTracked&&r.view!=='Sold')).length,0),reconnecting=blockerGroups().some(g=>g.type==='chrome')?1:0,disconnected=!nativeState.connected&&nativeState.jobs.some(j=>j.state==='queued')?1:0;return staticIssues+jobIssues+orphanJobs+reconnecting+disconnected}
function reviewAttentionJob(job,manual=false){const r=rows.find(r=>r.id===job?.itemId);if(!r){openActivity();return}if(job.kind==='publish'){openPublishRecovery(job);return}if(job.leadURL){leadSelection[r.id]=job.leadURL;if(manual){workFor(r).enabled=false;manualOpen.add(r.id+':'+job.leadURL)}}settings=false;category='All';selected=r.id;expandedListings.add(r.id);navigate(['Buying','Selling'].includes(r.view)?r.view:'Stock');if(manual)setTimeout(()=>$('#mp-manual-form textarea')?.focus(),0)}
function retryAttentionJob(job){if(!retryableJob(job)){feedback('A newer task already replaced this one.');return}job.state='queued';job.retryCount=0;job.retryAt=Date.now()+1000;job.note='Retrying this conversation safely.';const r=rows.find(r=>r.id===job.itemId);if(r){const remaining=latestItemJobs(r).some(j=>j!==job&&actionableJobIssue(j));workFor(r).needs=remaining}saveSoon();render();feedback('Retry queued. Vector will verify the conversation before sending.')}
function openAttention(){settings=true;settingsTitle='Needs attention';renderAttentionContent();render()}
function renderAttentionContent(){const items=attentionItems().map(x=>({...x,issues:x.issues.filter(i=>!i.job||i.edit)})).filter(x=>x.issues.length).sort((a,b)=>Number(!!b.restricted)-Number(!!a.restricted)),missing=items.filter(x=>x.issues.some(i=>i.title==='Needs photo')).length,queued=nativeState.jobs.some(j=>j.state==='queued');$('#mp-settings').innerHTML='<p class="va-summary">'+items.length+' items need attention'+(missing?' · '+missing+' need photos':'')+'</p>'+(!nativeState.connected&&queued?'<article class="va-issue"><strong>AI disconnected</strong><p>Connect your AI runtime to start queued work.</p><button class="mp-small-button" id="va-connect">Connections</button></article>':'')+items.map((x,n)=>{const itemKey='item:'+(x.restricted?'restricted:'+x.name:'row:'+x.r.id);return '<details class="va-issue" data-attention-key="'+esc(itemKey)+'"'+(x.restricted?' open':'')+'><summary><strong>'+esc(x.name)+'</strong><small>'+esc(x.issues.map(i=>i.title).join(' · '))+'</small></summary>'+x.issues.map((i,k)=>'<div><strong>⚠ '+esc(i.title)+'</strong><p>'+esc(i.detail)+'</p>'+(i.next?'<p>'+esc(i.next)+'</p>':'')+(i.evidence?'<details data-attention-key="'+esc(itemKey+':evidence:'+(i.job?.id||k))+'"><summary>Reported error</summary><p>'+esc(i.evidence)+'</p></details>':'')+'<button class="mp-small-button" data-va-item="'+n+'" data-va-issue="'+k+'">'+esc(i.action)+'</button></div>').join('')+'</details>'}).join('')+(!items.length?'<p>No listing issues detected.</p>':'');$('#va-connect')?.addEventListener('click',openConnections);$$('[data-va-item]').forEach(b=>b.onclick=()=>{const x=items[+b.dataset.vaItem],i=x.issues[+b.dataset.vaIssue];if(x.restricted){nativeCall('openMarketplace',{url:'https://www.facebook.com/marketplace/you/selling/'}).catch(e=>feedback(e.message));return}if(i.edit){openStockEdit(x.r);return}reviewAttentionJob(i.job)})}
function decorateAttention(){
 decorateBlockerNotice();
 if(!$('#va-style')){const s=document.createElement('style');s.id='va-style';s.textContent='.va-status{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0;font-size:12px}.va-status span{border:1px solid #344951;border-radius:6px;padding:5px 8px;color:#b9cbd0}.va-status span[data-live="true"]{color:#80e5be;border-color:#28604f}.va-status span[data-needs="true"]{color:#efc47c;border-color:#69512c}#mp-settings .va-issue{border:1px solid #69512c;border-radius:12px;padding:18px;margin:12px 0;background:#191d20}#mp-settings .va-issue>summary{cursor:pointer;list-style:none;font-size:14px;padding:0}#mp-settings .va-issue[open]>summary small{display:none}.va-issue>summary small{display:block;color:#efc47c;margin-top:8px}#mp-settings .va-issue[open]>summary{margin-bottom:18px}.va-issue h3{margin:0 0 14px;font-size:15px}.va-issue p{color:#b9cbd0;line-height:1.5;overflow-wrap:anywhere}.va-issue>div+div{border-top:1px solid #394044;padding-top:14px;margin-top:14px}.va-summary{color:#efc47c}#va-nav[data-count="true"]{color:#efc47c}';document.head.append(s)}
 const count=attentionIssueCount();let nav=$('#va-nav');if(!nav){nav=document.createElement('button');nav.id='va-nav';nav.dataset.section='Needs attention';nav.onclick=openAttention;$('.mp-nav-foot').before(nav)}nav.textContent='⚠ Needs attention'+(count?' ('+count+')':'');nav.dataset.count=String(count>0);nav.setAttribute('aria-pressed',String(settings&&settingsTitle==='Needs attention'));
 const toolbarState=$('.mp-toolbar-state');if(toolbarState&&['Selling','Buying'].includes(view))toolbarState.textContent=laneEnabled[view]?'AI available':'AI paused';
 if(settings){if(settingsTitle==='Needs attention')renderAttentionContent();return}
 const badge=r=>{if(r.view==='Selling'){const s=sellingStatus(r);return '<div class="va-status"><span data-live="'+!!r.liveURL+'">Listing: '+esc(listingLabel(r))+'</span><span>Monitoring: '+esc(s.monitor)+'</span><span>Replies: '+esc(s.replies)+'</span>'+(s.action?'<span>'+esc(s.action)+'</span>':'')+(s.messageIssue?'<span data-needs="true">'+s.messageIssueCount+' conversation'+(s.messageIssueCount===1?'':'s')+' need review</span>':'')+'</div>'}const issue=buyingCardIssue(r),listing=r.view==='Buying'?'<span>Seller listing: Marketplace</span>':'<span data-live="'+!!r.liveURL+'">Listing: '+esc(listingLabel(r))+'</span>';return '<div class="va-status">'+listing+'<span data-needs="'+!!issue+'">'+(issue?esc(issue.title):'Automation: '+esc(automationLabel(r)))+'</span></div>'};
 $$('details.mp-work-card').forEach(card=>{const r=rows.find(r=>r.id===+card.dataset.id);if(!r)return;card.querySelector('.va-status')?.remove();card.querySelector('.va-card-issue')?.remove();card.querySelector('summary').insertAdjacentHTML('beforeend',badge(r));const issue=buyingCardIssue(r),content=card.querySelector('.mp-work-content');if(issue&&content){content.insertAdjacentHTML('afterbegin','<section class="va-card-issue"><strong>⚠ '+esc(issue.title)+'</strong><p>'+esc(issue.detail)+'</p><small>'+esc(issue.next)+'</small><div class="va-card-issue-actions">'+(issue.type==='distance'?'<button type="button" class="mp-action" data-keep-buying="'+r.id+'">Keep negotiating</button><button type="button" class="mp-small-button" data-pass-buying="'+r.id+'">Pass on deal</button><button type="button" class="mp-small-button" data-change-distance="'+r.id+'">Change limit</button>':'<button type="button" class="mp-small-button" data-review-buying="'+r.id+'">Review task</button>')+'</div></section>');content.querySelector('[data-keep-buying]')?.addEventListener('click',()=>keepBuyingProspect(r));content.querySelector('[data-pass-buying]')?.addEventListener('click',()=>{closeBuyingProspect(r);render();saveSoon()});content.querySelector('[data-change-distance]')?.addEventListener('click',()=>openAutomationResolution({side:'Buying',title:issue.title,detail:'Increase Search within if you want Vector to continue deals at this distance.',page:'buying',target:'[name="radius"]'}));content.querySelector('[data-review-buying]')?.addEventListener('click',()=>reviewAttentionJob(latestItemJobs(r).find(actionableJobIssue)))}const state=card.querySelector('.mp-glance-state');if(state){state.hidden=true;if(state.previousElementSibling?.getAttribute('aria-hidden')==='true')state.previousElementSibling.hidden=true};const expanded=card.querySelector('.mp-work-state');if(expanded){const s=r.view==='Selling'?sellingStatus(r):null;expanded.textContent=s?(s.action||'Monitoring: '+s.monitor+' · Replies: '+s.replies):'Automation: '+automationLabel(r);expanded.classList.toggle('mp-attention',s?s.messageIssue:automationLabel(r)==='Needs attention')}const last=card.querySelector('.mp-work-last');if(last)last.hidden=true;const next=card.querySelector('.mp-work-next');if(next)next.textContent=!laneEnabled[r.view]?r.view+' automation paused':r.view==='Selling'?(workFor(r).enabled?'Automatic replies enabled':'Automatic replies off'):(issue?issue.next:workFor(r).enabled?'Auto-negotiation enabled':'Auto-negotiation off')});
 $$('.inv-card').forEach(card=>{const r=rows.find(r=>r.id===+card.querySelector('[data-stock-edit]')?.dataset.stockEdit);if(!r)return;const body=card.querySelector('[data-stock-edit]').parentElement;body.querySelectorAll('.va-status').forEach(x=>x.remove());const ps=body.querySelectorAll('p');if(ps[1])ps[1].outerHTML=badge(r);const note=body.querySelector('small');if(note)note.textContent=!photos[r.photo]?'⚠ Needs photo':latestItemJobs(r).some(j=>['failed','needs_you'].includes(j.state))?'':r.liveURL?(r.pricing?'Market estimate '+money(r.pricing.ask)+' · Minimum '+money(r.minimum):''):r.inventoryNote||''});
 $$('.inv-table tbody tr').forEach(tr=>{const r=rows.find(r=>r.id===+tr.querySelector('[data-stock-edit]')?.dataset.stockEdit);if(r){tr.cells[6].textContent=listingLabel(r);if(r.view==='Selling'){const s=sellingStatus(r);tr.cells[7].textContent=s.action||'Monitoring: '+s.monitor+' · Replies: '+s.replies}else tr.cells[7].textContent='Automation: '+automationLabel(r)}});
 if(['Selling','Buying'].includes(view)){const r=rows.find(r=>r.id===selected);if(r){const head=$('#mp-detail .mp-comms-head');if(head&&!head.querySelector('.va-status'))head.insertAdjacentHTML('beforeend',badge(r));const next=$('#mp-detail .mp-next-action');if(next){if(view==='Selling'){const s=sellingStatus(r);next.textContent=s.action||'Monitoring: '+s.monitor+' · Replies: '+s.replies}else next.textContent='Automation: '+automationLabel(r)}const toggle=$('#mp-work-toggle'),w=workFor(r);if(toggle){toggle.textContent=w.enabled?'Pause AI replies':'Enable AI replies';if(!w.enabled&&automationLabel(r)==='Needs attention'&&!(r.importedLive&&r.pricing&&!w.importBaseline)){toggle.textContent='Review issue';toggle.disabled=false;toggle.onclick=openAttention}else if(!w.enabled&&r.importedLive&&(!r.pricing||w.importBaseline)){toggle.textContent='Waiting for checks';toggle.disabled=true;}} } }
 if(['Selling','Stock'].includes(view)&&restrictedItems().length){const bar=$('#mp-toolbar'),b=document.createElement('button');b.className='mp-small-button';b.textContent='⚠ '+restrictedItems().length+' restricted';b.onclick=openAttention;bar.append(b)}
}
function blockerGroups(){
 const latest=new Map();for(const j of nativeState.jobs)latest.set((j.itemId??'workspace')+':'+jobScopeKey(j),j);
 const groups=new Map();for(const j of latest.values()){
  if(!['needs_you','failed'].includes(j.state)||/^Stopped\.|^Work paused\./i.test(j.note||''))continue;
  const note=j.note||'',type=/^Pickup is [\d.]+ km\. Review this deal before replying\.$/i.test(note)?'deal':j.kind==='reply'&&/composer|approved (?:text|response)|message entry|step limit|delivery not verified/i.test(note)?'composer':/usage limit|rate limit|quota/i.test(note)?'runtime':/PIN|restore.*(?:chat|history)|history.*restor/i.test(note)?'history':/sign.?in|log.?in|CAPTCHA|(?:Facebook|account|identity|security).{0,30}verif|verif.{0,30}(?:Facebook|account|identity|security)/i.test(note)?'login':/companion.*update|running companion|reload.*extension/i.test(note)?'extension':'task';
  const key=type==='task'?type+':'+j.kind+':'+note:type;
  if(!groups.has(key))groups.set(key,{key,type,jobs:[]});groups.get(key).jobs.push(j);
 }
 const reconnecting=nativeState.jobs.filter(j=>j.state==='queued'&&(j.retryCount||0)>=3&&j.retryAt);if(reconnecting.length)groups.set('chrome-reconnect',{key:'chrome-reconnect',type:'chrome',jobs:reconnecting});
 return [...groups.values()].map(g=>({...g,
  title:g.type==='deal'?'Pickup distance needs review':g.type==='composer'?'Buyer replies need attention':g.type==='runtime'?(nativeState.connected?'AI connected · Tasks awaiting retry':'Tasks stopped at AI usage limit'):g.type==='history'?'Restore your Messenger chats':g.type==='login'?'Facebook needs verification':g.type==='extension'?'Update the Chrome companion':g.type==='chrome'?'Chrome connection lost':'Automation needs your attention',
  detail:g.type==='deal'?'This seller is outside your automatic distance limit. Review the deal and choose whether to continue.':g.type==='composer'?'Facebook did not accept these replies. Vector retries transient failures automatically. You can retry or write each reply yourself.':g.type==='runtime'?(nativeState.connected?'Your AI connection passed. Review and retry the tasks stopped by the earlier usage limit.':'These tasks hit a usage limit. Check your AI connection, then review and retry them.'):g.type==='history'?'Complete the history-restoration prompt in Chrome, then retry the blocked tasks.':g.type==='login'?'Complete Facebook verification in Chrome, then retry.':g.type==='extension'?'Update the Vector companion in Chrome, then check the connection.':g.type==='chrome'?'Vector is retrying automatically. Open Connections if Chrome stays unavailable.':(taskNames[g.jobs[0].kind]||'This task')+' stopped. Review the reported error before retrying.',
  token:JSON.stringify([g.key,g.jobs.map(j=>j.id).sort()])}));
}
let blockerBadgeCount=-1;
let distanceSettingsBannerSuppressed=false;
function decorateBlockerNotice(){
 const groups=blockerGroups(),tokens=groups.map(g=>g.token);
 nativeState.dismissedBlockers=(nativeState.dismissedBlockers||[]).filter(k=>tokens.includes(k));
 nativeState.notifiedBlockers=(nativeState.notifiedBlockers||[]).filter(k=>tokens.includes(k));
 const unseen=groups.filter(g=>!nativeState.notifiedBlockers.includes(g.token));
 const badgeCount=attentionIssueCount()+activePickups().length;
 if(nativeReady&&(unseen.length||badgeCount!==blockerBadgeCount)){blockerBadgeCount=badgeCount;nativeState.notifiedBlockers.push(...unseen.map(g=>g.token));nativeCall('attention',{count:badgeCount,notify:unseen.length>0}).catch(()=>{});for(const g of unseen)notifyOnce('blocker:'+g.token,'Vector needs attention',g.title+' · '+g.jobs.length+' task'+(g.jobs.length===1?'':'s')+' waiting',g.jobs.find(j=>j.itemId)?.itemId||null,'Needs attention');saveSoon()}
 let visible=groups.filter(g=>!nativeState.dismissedBlockers.includes(g.token));let banner=$('#va-blocker');
 if(settings&&settingsTitle==='Needs attention'){banner?.remove();return}
 if(settings&&settingsTitle==='Buying settings'&&distanceSettingsBannerSuppressed)visible=visible.filter(g=>g.type!=='deal');
 if(!(settings&&settingsTitle==='Buying settings'))visible=visible.filter(g=>g.type!=='deal');
 if(!visible.length){banner?.remove();return}
 if(!banner){banner=document.createElement('section');banner.id='va-blocker';banner.setAttribute('role','status');banner.setAttribute('aria-live','polite');$('#mp-toolbar').before(banner)}
 const g=visible[0],distanceCount=g.type==='deal'?g.jobs.length:0,title=settings&&distanceCount?'Pickup limit affects '+distanceCount+' deal'+(distanceCount===1?'':'s'):g.title,detail=settings&&distanceCount?'Some buying deals are outside your pickup limit. Review them or adjust Search within.':g.detail,signature=JSON.stringify(visible.map(x=>[x.token,title,detail]));if(banner.dataset.signature===signature)return;banner.dataset.signature=signature;
 banner.innerHTML='<div><strong>⚠ '+esc(title)+'</strong><p>'+esc(detail)+'</p><small>'+attentionIssueCount()+' issues need attention</small></div><div class="va-blocker-actions"><button type="button" class="mp-action" id="va-blocker-review">Resolve</button><button type="button" class="mp-small-button" id="va-blocker-dismiss">Dismiss</button></div>';
 $('#va-blocker-review').onclick=openAttention;$('#va-blocker-dismiss').onclick=()=>{nativeState.dismissedBlockers.push(...visible.map(x=>x.token));saveSoon();decorateBlockerNotice()};
}
const renderListingAttentionContent=renderAttentionContent;
renderAttentionContent=function(){const openKeys=new Set($$('#mp-settings details[open][data-attention-key]').map(x=>x.dataset.attentionKey));renderListingAttentionContent();const groups=blockerGroups(),summary=$('#mp-settings .va-summary');if(summary)summary.textContent=attentionIssueCount()+' issues need attention';if(!groups.length){$$('#mp-settings details[data-attention-key]').forEach(x=>x.open=openKeys.has(x.dataset.attentionKey)||x.open);return}
 const taskLabel=j=>{const r=rows.find(r=>r.id===j.itemId),lead=r&&j.leadURL?workFor(r).leads.find(l=>l.url===j.leadURL):null;return (r?.name||taskNames[j.kind]||'Workspace')+(lead?' · '+lead.id:'')};
 const panel=document.createElement('section');panel.id='va-blocked-tasks';panel.innerHTML=groups.map((g,n)=>'<article class="va-issue"><strong>⚠ '+esc(g.title)+'</strong><p>'+esc(g.detail)+'</p>'+g.jobs.map((j,k)=>'<div class="va-task-row"><span>'+esc(taskLabel(j))+'</span><span class="va-task-actions"><button type="button" class="mp-small-button" data-blocker-job="'+n+':'+k+'">'+(rows.some(r=>r.id===j.itemId)?(g.type==='deal'?'Review deal':j.kind==='reply'?'Open conversation':'Review item'):'Open task log')+'</button>'+(j.kind==='reply'?'<button type="button" class="mp-small-button" data-blocker-retry="'+n+':'+k+'">Retry</button><button type="button" class="mp-small-button" data-blocker-manual="'+n+':'+k+'">Write reply</button>':'')+'</span></div>').join('')+'<details data-attention-key="'+esc('blocker:'+g.token)+'"><summary>'+(g.type==='deal'?'Why it paused':'Reported error')+'</summary><p>'+esc(g.jobs[0].note||'No details available.')+'</p></details>'+(g.type!=='task'&&g.type!=='deal'&&g.type!=='composer'?'<button type="button" class="mp-small-button" data-blocker-open="'+n+'">'+(['extension','runtime','chrome'].includes(g.type)?'Connections':'Open Chrome')+'</button>':'')+'</article>').join('');if(summary)summary.after(panel);else $('#mp-settings').prepend(panel);
 $$('#mp-settings details[data-attention-key]').forEach(x=>x.open=openKeys.has(x.dataset.attentionKey)||x.open);
 panel.querySelectorAll('[data-blocker-open]').forEach(b=>b.onclick=()=>{const g=groups[+b.dataset.blockerOpen];if(['extension','runtime','chrome'].includes(g.type))openConnections();else nativeCall('showChrome').catch(e=>feedback(e.message))});panel.querySelectorAll('[data-blocker-job]').forEach(b=>b.onclick=()=>{const [groupIndex,jobIndex]=b.dataset.blockerJob.split(':').map(Number);reviewAttentionJob(groups[groupIndex].jobs[jobIndex])});panel.querySelectorAll('[data-blocker-retry]').forEach(b=>b.onclick=()=>{const [groupIndex,jobIndex]=b.dataset.blockerRetry.split(':').map(Number);retryAttentionJob(groups[groupIndex].jobs[jobIndex])});panel.querySelectorAll('[data-blocker-manual]').forEach(b=>b.onclick=()=>{const [groupIndex,jobIndex]=b.dataset.blockerManual.split(':').map(Number);reviewAttentionJob(groups[groupIndex].jobs[jobIndex],true)});
};
