// Icons are bundled from the vendors' installed Mac applications.
const connectionChecks={};
let lastChromeHealthMessage='';
function updateCompanionHealth(status,error=''){const issue=error||(status?companionIssue(status):'Disconnected'),el=$('[data-health="Chrome"]'),note=$('#native-connection-status');if(el){el.textContent=error?'Disconnected':issue?(status?.tabConnected?'Update needed':'Open Marketplace'):'Connected';el.dataset.connected=String(!issue)}connectionChecks.Chrome=issue?0:Date.now();if(note&&lastChromeHealthMessage&&note.textContent===lastChromeHealthMessage)note.textContent=issue;lastChromeHealthMessage=issue;}

function runtimeConnectionNotice(){if(nativeState.runtimeBlockKind==='usage')return {title:'AI usage limit reached',detail:'Your AI provider reported a usage limit. Marketplace AI checks again automatically. If usage is available now, open Connections and check the AI connection.'};if(nativeState.runtimeBlockKind==='setup')return {title:'AI sign-in needs attention',detail:'Sign into the selected AI provider on this Mac, then check its connection.'};return {title:'AI disconnected',detail:'Connect your AI runtime to start queued work.'};}
function companionIssue(s){if(!s.tabConnected)return 'Open Facebook Marketplace in Chrome. Marketplace AI will connect automatically.';if(s.readiness!=='document-v6')return 'Reload the Marketplace AI in Chrome Extensions, then retry this task. The running companion needs an update.';return '';}
function companionRecoveryNote(note){return /running companion needs an update|open Facebook Marketplace in Chrome|Chrome reconnecting|Chrome (?:connection )?(?:lost|disconnected)|native host.*disconnect/i.test(note||'')}
function recoverCompanionJobs(){let changed=false;for(const j of nativeState.jobs.filter(j=>['needs_you','queued'].includes(j.state)&&companionRecoveryNote(j.note))){if(j.state==='needs_you'){j.state=j.kind==='poll'?'cancelled':'queued';j.note=j.kind==='poll'?'Superseded after the companion reconnected.':'Companion reconnected. Queued for retry.'}else j.note='Chrome reconnected. Queued for retry.';delete j.retryAt;delete j.retryCount;changed=true}if(changed){saveSoon();decorateAttention()}return changed}
function openConnections(){
 settings=true;settingsTitle='Connections';
 const providers=[['Codex','codex'],['Claude Code','claude']];
 $('#mp-settings').innerHTML='<div class="vx-connections">'+providers.map(([name,icon])=>'<article class="vx-connection" data-provider-card="'+name+'"><img src="assets/'+icon+'.png" alt="'+name+'" width="72" height="72"><h3>'+name+'</h3><span class="vx-health" data-health="'+name+'">Not checked</span><p>'+(name===nativeState.provider?'Selected AI runtime':'Use your existing subscription')+'</p><button class="mp-small-button" '+(name===nativeState.provider?'id="native-test" ':'')+'data-connect-provider="'+name+'">'+(name===nativeState.provider&&nativeState.connected?'Check '+name:'Connect '+name)+'</button></article>').join('')+'<article class="vx-connection" data-provider-card="Chrome"><img src="assets/chrome.png" alt="Google Chrome" width="72" height="72"><h3>Chrome</h3><span class="vx-health" data-health="Chrome">Checking…</span><p>Your signed-in Marketplace session</p><button class="mp-small-button" id="native-store">Install companion</button><button class="mp-small-button" id="native-market">Open Marketplace</button><button class="mp-small-button" id="native-chrome-test">Check connection</button></article></div><p id="native-connection-status" role="status"></p><details class="vx-support"><summary>Setup & tools</summary><p>Sign into the official Codex or Claude Code CLI on this Mac. Install the companion from the Chrome Web Store. No API key is needed.</p><div class="vx-actions"><button class="mp-small-button" id="native-setup">Setup guide</button><button class="mp-small-button" id="native-extension">Developer extension folder</button><button class="mp-small-button" id="native-folder">Local data</button></div></details><select id="native-provider" hidden><option>Codex</option><option>Claude Code</option></select><button class="mp-small-button" id="native-back">Back</button>';
 render();const select=$('#native-provider');select.value=nativeState.provider;select.disabled=workerBusy;
 const health=(name,label,ok=false)=>{const el=$('[data-health="'+name+'"]');if(el){el.textContent=label;el.dataset.connected=String(ok)}};
 for(const [name] of providers){const check=connectionChecks[name];if(name===nativeState.provider&&!nativeState.connected&&nativeState.runtimeBlockKind)health(name,runtimeConnectionNotice().title);else if(check&&Date.now()-check<300000)health(name,'Connected',true);else if(name===nativeState.provider&&nativeState.connected)health(name,'Ready',true);}
 nativeCall('runtimeStatus').then(s=>providers.forEach(([name])=>{if(s[name]===false)health(name,'CLI not installed')})).catch(()=>{});
 const checkChrome=async()=>{try{const s=await nativeCall('chromeStatus'),issue=companionIssue(s);health('Chrome',issue?(s.tabConnected?'Update needed':'Open Marketplace'):'Connected',!issue);connectionChecks.Chrome=issue?0:Date.now();const status=$('#native-connection-status');if(status)status.textContent=issue;if(!issue){recoverCompanionJobs();const card=$('[data-provider-card="Chrome"]');card?.classList.remove('vx-guidance-target');card?.querySelector('.vx-field-guidance')?.remove();const guidance=$('#vx-automation-guidance');if(guidance&&/Browser connection/i.test(guidance.textContent))guidance.remove()}const support=$('.vx-support');if(support){let diagnostic=$('#vx-companion-build');if(!diagnostic){diagnostic=document.createElement('p');diagnostic.id='vx-companion-build';support.append(diagnostic)}diagnostic.textContent='Running companion: '+(s.version||'unknown')+' · '+(s.readiness||'legacy readiness')}}catch(e){health('Chrome','Disconnected');const status=$('#native-connection-status');if(status)status.textContent=e.message}};
 $('#native-chrome-test').onclick=checkChrome;checkChrome();
 const test=async(name,button)=>{if(workerBusy){feedback('Wait for the current AI task to finish.');return}const status=$('#native-connection-status');nativeState.provider=name;nativeState.connected=false;select.value=name;button.disabled=true;select.disabled=true;health(name,'Connecting…');try{const result=await infer('Return status ready. No tools.',objectSchema({status:{type:'string'}}));if(result.status!=='ready')throw Error('Unexpected AI response.');nativeState.connected=true;connectionChecks[name]=Date.now();health(name,'Connected',true);button.textContent='Check '+name;status.textContent=name+' is ready.';addActivity(name+' connection verified')}catch(e){connectionChecks[name]=0;health(name,nativeState.runtimeBlockKind?runtimeConnectionNotice().title:'Connection failed');status.textContent=e.message}finally{button.disabled=false;select.disabled=workerBusy;decorateBlockerNotice();saveSoon()}};
 $$('[data-connect-provider]').forEach(b=>{b.disabled=workerBusy;b.onclick=()=>test(b.dataset.connectProvider,b)});
 $('#native-store').onclick=()=>nativeCall('openCompanionStore',{url:VECTOR_COMPANION_STORE_URL}).catch(e=>feedback(e.message));$('#native-market').onclick=()=>nativeCall('openMarketplace').then(checkChrome).catch(e=>feedback(e.message));$('#native-setup').onclick=()=>openVectorOnboarding({review:true});$('#native-extension').onclick=()=>nativeCall('showExtension');$('#native-folder').onclick=()=>nativeCall('showData');$('#native-back').onclick=()=>{settings=false;render()};
}
