// A historical inbox can exceed one model/browser task. Persist discovery and
// each verified thread independently so interrupted imports resume their work.
function sameThreadAddress(a,b){return typeof a==='string'&&typeof b==='string'&&a.replace(/\/$/,'')===b.replace(/\/$/,'')}
function inboxKey(x){return x?.key||String(x?.label||'').trim()}
function conversationProgress(job,r){
 const w=typeof workFor==='function'?workFor(r):null,prior=typeof nativeState==='object'&&Array.isArray(nativeState.jobs)?nativeState.jobs.filter(j=>j.itemId===r.id&&j.conversationProgress).sort((a,b)=>Object.keys(b.conversationProgress.reads||{}).length-Object.keys(a.conversationProgress.reads||{}).length)[0]?.conversationProgress:null;
 const ownsJob=job.kind!=='poll'&&(job.itemId==null||job.itemId===r.id),p=w?.conversationProgress||(ownsJob?job.conversationProgress:null)||prior||{candidates:[],reads:{},censusComplete:false,coverage:''};if(w){w.conversationProgress=p;if(ownsJob)delete job.conversationProgress}else if(ownsJob)job.conversationProgress=p;return p;
}
function mergeInboxCandidates(p,found){p.candidates=[...new Map([...p.candidates,...found].map(x=>[inboxKey(x),x])).values()]}
function normalizedInboxText(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/[^\p{L}\p{M}\p{N}]+/gu,' ').trim()}
function inboxIdentity(row){return row?.url&&typeof validThreadURL==='function'&&validThreadURL(row.url)?String(row.url).replace(/\/$/,''):normalizedInboxText(row?.person)+'|'+normalizedInboxText(row?.listing)}
function compactConversationText(value,needle){const text=String(value||''),limit=6000;if(text.length<=limit)return text;const at=text.lastIndexOf(String(needle||'')),start=at<0?text.length-limit:Math.max(0,Math.min(at-3000,text.length-limit));return text.slice(start,start+limit)}
function matchInboxListing(row,monitored){const title=normalizedInboxText(row.listing),matches=monitored.filter(r=>{const item=normalizedInboxText(r.name);return title&&item&&(title===item||(title.length>12&&item.includes(title))||(item.length>12&&title.includes(item)))});return matches.length===1?matches[0]:null}
function groupedInboxRows(inboxRows,monitored){const groups=new Map();for(const row of inboxRows){const r=matchInboxListing(row,monitored);if(!r)continue;const key=inboxIdentity(row),groupKey=r.id+'|'+key,signature=normalizedInboxText(row.preview);let group=groups.get(groupKey);if(!group){group={r,key,rows:[],signatures:new Set()};groups.set(groupKey,group)}group.rows.push(row);group.signatures.add(signature)}return [...groups.values()].map(group=>{group.rows.sort((a,b)=>{const length=normalizedInboxText(b.preview).length-normalizedInboxText(a.preview).length;return length||String(a.label||'').localeCompare(String(b.label||''))});return {r:group.r,key:group.key,row:group.rows[0],signature:[...group.signatures].sort().join(' || ')}})}
function activateSellingReplies(r,{includeCurrent=false}={}){
 const w=workFor(r);if(r.view!=='Selling'||!laneEnabled.Selling||!w.enabled||w.importBaseline)return 0;let queued=0;
 if(includeCurrent)for(const lead of w.leads||[])if(lead.unanswered===true&&lead.last?.trim())delete lead.replyBaseline;
 for(const lead of w.leads||[])if(validThreadURL(lead.url)&&lead.last?.trim()&&lead.unanswered===true&&lead.repliedTo!==lead.last&&lead.replyBaseline!==lead.last){if(queueJob('reply',r,{leadURL:lead.url,incoming:lead.last}))queued++}
 const pending=w.pendingInboxChanges||[],p=conversationProgress({kind:'sync',itemId:r.id},r),people=new Set(pending.map(x=>normalizedInboxText(x.person))),keys=new Set(pending.map(x=>x.key).filter(Boolean));for(const candidate of p.candidates||[])if(people.has(normalizedInboxText(candidate.person)))keys.add(inboxKey(candidate));for(const key of keys)delete p.reads[key];if(keys.size)queueJob('sync',r,{recurring:true,incremental:true,targetCandidateKeys:[...keys]});else if(!queued)queueJob('sync',r);delete w.pendingInboxChanges;return queued
}
async function pollInbox(job){
 const side=job.side==='Buying'?'Buying':'Selling',monitored=rows.filter(r=>r.view===side&&monitoringWanted(r));if(!monitored.length){job.routineOnly=true;if(typeof routineRenderPending!=='undefined')routineRenderPending=true;job.completionNote='Monitoring is off.';return}
 const target=side==='Buying'?'BUYER':'SELLER',inbox='https://www.facebook.com/marketplace/inbox?targetTab='+target;await nativeCall('browserAction',{action:'navigate',url:inbox});await delay(900);let observed=await nativeCall('observeInbox');if(!(observed.url||'').includes('/marketplace/inbox')||!Array.isArray(observed.inboxRows))throw Error(side+' inbox could not be checked. No AI request was used.');let entries=groupedInboxRows(observed.inboxRows,monitored),priorMatched=nativeState['inboxMatched'+side]||0;for(let attempt=0;attempt<3&&priorMatched>=10&&entries.length<priorMatched*.75;attempt++){await delay(700);observed=await nativeCall('observeInbox');entries=groupedInboxRows(observed.inboxRows||[],monitored)}
 const metrics=nativeState.metrics||(nativeState.metrics={});metrics.inboxPolls=(metrics.inboxPolls||0)+1;metrics[side.toLowerCase()+'InboxPolls']=(metrics[side.toLowerCase()+'InboxPolls']||0)+1;metrics.lastInboxPoll=Date.now();nativeState.lastInboxPoll=metrics.lastInboxPoll;if(priorMatched>=10&&entries.length<priorMatched*.75){const signature=entries.map(x=>x.key).sort().join('|'),candidate=nativeState.inboxPartialCoverage?.[side],repeats=candidate?.signature===signature?(candidate.repeats||0)+1:1;nativeState.inboxPartialCoverage||(nativeState.inboxPartialCoverage={});nativeState.inboxPartialCoverage[side]={signature,repeats,matched:entries.length};metrics.partialInboxPolls=(metrics.partialInboxPolls||0)+1;if(repeats<3){job.completionNote=side+' inbox still loading · '+entries.length+' of '+priorMatched+' matched · no AI used';return}}else if(nativeState.inboxPartialCoverage)delete nativeState.inboxPartialCoverage[side];
 nativeState['inboxMatched'+side]=entries.length;const versionKey='inboxFingerprintVersion'+side,initializing=nativeState[versionKey]!==2&&!(side==='Selling'&&nativeState.inboxFingerprintVersion===2);let changes=0,matched=0;const changedByItem=new Map();for(const entry of entries){const {r,key,row,signature}=entry;matched++;const w=workFor(r),p=conversationProgress(job,r);let candidate=p.candidates.find(x=>x.key===key)||p.candidates.find(x=>normalizedInboxText(x.person)===normalizedInboxText(row.person));
  if(candidate&&candidate.key!==key){const old=candidate.key||candidate.label;candidate.key=key;if(p.reads[old]&&!p.reads[key])p.reads[key]=p.reads[old];delete p.reads[old];w.inboxFingerprints||(w.inboxFingerprints={});if(w.inboxFingerprints[old]!==undefined&&w.inboxFingerprints[key]===undefined)w.inboxFingerprints[key]=w.inboxFingerprints[old];delete w.inboxFingerprints[old]}
  const wasKnown=!!candidate;if(!candidate){candidate={key,label:row.label,person:row.person,url:row.url||''};mergeInboxCandidates(p,[candidate])}else{candidate.label=row.label;candidate.person=row.person;if(typeof validThreadURL==='function'&&validThreadURL(row.url))candidate.url=row.url}
  const previous=w.inboxFingerprints?.[key];w.inboxFingerprints||(w.inboxFingerprints={});w.inboxFingerprints[key]=signature;const hasRead=!!p.reads[key],ownPreview=side==='Buying'&&(w.leads||[]).some(lead=>normalizedInboxText(lead.reply)===signature),changed=!initializing&&!ownPreview&&((previous!==undefined&&previous!==signature)||(!wasKnown&&!hasRead));if(changed){delete p.reads[key];if(!changedByItem.has(r))changedByItem.set(r,[]);changedByItem.get(r).push({key,person:String(row.person||'Buyer').trim()||'Buyer',preview:String(row.preview||'').trim().slice(0,240)});changes++}
 }
 nativeState.inboxInitialized=true;nativeState[versionKey]=2;if(side==='Selling')nativeState.inboxFingerprintVersion=2;let held=0;for(const [r,changedRows] of changedByItem){const w=workFor(r),keys=[...new Set(changedRows.map(x=>x.key))];if(w.enabled)queueJob('sync',r,{recurring:true,incremental:true,targetCandidateKeys:keys});else{held+=changedRows.length;w.pendingInboxChanges=changedRows.slice(-5).map(x=>({key:x.key,person:x.person,preview:x.preview,detectedAt:new Date().toISOString()}));const people=[...new Set(changedRows.map(x=>x.person))];w.last='Inbox changed for '+people.slice(0,2).join(', ')+(people.length>2?' and '+(people.length-2)+' more':'')+'. AI replies are off.';w.updated='Now'}}metrics.inboxChanges=(metrics.inboxChanges||0)+changes;if(held)metrics.inboxChangesHeld=(metrics.inboxChangesHeld||0)+held;if(changes)metrics.pollsWithChanges=(metrics.pollsWithChanges||0)+1;if(changes){nativeState['lastInboxChange'+side]=Date.now();nativeState['nextInboxPoll'+side]=Date.now()+15000}job.routineOnly=!initializing&&changes===0;if(job.routineOnly&&typeof routineRenderPending!=='undefined')routineRenderPending=true;job.completionNote=side+' inbox checked · '+matched+' matched · '+changes+' changed · no AI used'+(held?' · '+held+' held with AI off':'');
}
function threadResultIssue(result,evidence,r){const lead=result.lead,listingURL=r.liveURL||r.url;if(!validThreadURL(lead?.url)||!evidence.some(o=>sameThreadAddress(o.url,lead.url)))return 'The result must use the actual Messenger thread URL from your observations. Reuse evidence already collected.';const pages=evidence.filter(o=>sameThreadAddress(o.url,lead.url));if(typeof lead.last!=='string'||!lead.last.trim()||!pages.some(o=>o.text.includes(lead.last)))return 'The reported latest message is not present in the observed thread. Quick-response suggestions and message-action controls are interface elements, not incoming messages. Recheck the existing observations for the latest actual message and return its exact text. Do not invent content or substitute an explanation for message text. If genuinely unreadable, report needs_user.';if(!pages.some(o=>o.text.includes(lead.last)&&(o.listings||[]).some(l=>marketplaceID(l.url)===marketplaceID(listingURL))))return 'The thread must show a listing banner matching the requested listing URL together with the returned message. Verify the correct conversation.';return ''}
function buyingThreadResultIssue(result,evidence,r,candidate,knownURL){
 const issue=threadResultIssue(result,evidence,r);if(!issue||!issue.startsWith('The thread must show a listing banner'))return issue;
 const lead=result.lead,pages=evidence.filter(o=>sameThreadAddress(o.url,lead?.url)),title=normalizedInboxText(r.name),seller=normalizedInboxText(candidate?.person);
 const savedIdentity=validThreadURL(knownURL)&&sameThreadAddress(knownURL,lead?.url)&&seller&&normalizedInboxText(lead?.id)===seller;
 const visibleIdentity=pages.some(o=>normalizedInboxText(o.text).includes(title)&&normalizedInboxText(o.text).includes(seller));
 return savedIdentity&&visibleIdentity?'':issue;
}
async function discoverInboxCandidates(job,r,p,inbox){
 const generation=typeof stopGeneration==='number'?stopGeneration:0;let stableEnds=0,lastLabels='',complete=false,scrolls=0;
 await nativeCall('browserAction',{action:'navigate',url:inbox});if(typeof delay==='function')await delay(900);
 for(let step=0;step<48;step++){
  if((typeof stopGeneration==='number'&&generation!==stopGeneration)||(typeof jobAllowed==='function'&&!jobAllowed(job)))throw Error('Work paused.');
  const observed=await nativeCall('observe');if(!(observed.url||'').includes('/marketplace/inbox')||!Array.isArray(observed.inboxRows))throw Error('Selling inbox could not be read. No AI request was used.');
  const found=observed.inboxRows.filter(row=>matchInboxListing(row,[r])===r).map(row=>({key:inboxIdentity(row),label:row.label,person:row.person,url:row.url&&validThreadURL(row.url)?row.url:''}));mergeInboxCandidates(p,found);saveSoon();
  const labels=JSON.stringify(observed.inboxRows.map(row=>row.label)),target=(observed.nodes||[]).filter(node=>node.kind==='inbox-conversation').at(-1);if(!target)break;
  const result=await nativeCall('browserAction',{action:'scroll',id:target.id,value:'down',epoch:observed.epoch});scrolls++;const loading=Array.isArray(observed.loading)?observed.loading:[];
  stableEnds=result?.atEnd===true&&result?.scrolled===false&&!loading.length&&labels===lastLabels?stableEnds+1:result?.atEnd===true&&result?.scrolled===false&&!loading.length?1:0;lastLabels=labels;
  const metrics=typeof nativeState==='object'?(nativeState.metrics||(nativeState.metrics={})):{};metrics.inboxHistoryScrolls=(metrics.inboxHistoryScrolls||0)+1;job.note='Scanning inbox history locally · '+p.candidates.length+' matching chats · no AI used';saveSoon();if(typeof refreshActivity==='function')refreshActivity();
  if(stableEnds>=2){complete=true;break}if(typeof delay==='function')await delay(result?.scrolled?350:700);
 }
 p.coverage=complete?'Reached the stable end of the Selling inbox after '+scrolls+' local scrolls.':'Paused after '+scrolls+' local scrolls; older inbox history remains unchecked.';p.censusComplete=complete;p.censusVersion=4;saveSoon();return complete;
}
function knownBuyingThread(w,candidate){
 const person=normalizedInboxText(candidate?.person),valid=(w.leads||[]).filter(lead=>validThreadURL(lead.url));
 const exact=valid.filter(lead=>person&&normalizedInboxText(lead.id)===person);
 return exact.length===1?exact[0].url:valid.length===1?valid[0].url:'';
}
async function openBuyingThread(r,w,candidate){
 const known=knownBuyingThread(w,candidate);
 if(known){await nativeCall('browserAction',{action:'navigate',url:known});await delay(500);const observed=await nativeCall('observe');if(validThreadURL(observed.url))return observed}
 const inbox='https://www.facebook.com/marketplace/inbox?targetTab=BUYER';await nativeCall('browserAction',{action:'navigate',url:inbox});await delay(900);let observed=await nativeCall('observe'),row=observed.nodes.find(node=>node.kind==='inbox-conversation'&&normalizedInboxText(node.label).includes(normalizedInboxText(candidate.person))&&normalizedInboxText(node.label).includes(normalizedInboxText(r.name)));
 if(!row)throw Error('Temporary Facebook UI: the matching seller conversation is not visible yet.');
 await nativeCall('browserAction',{action:'click',id:row.id,epoch:observed.epoch});await delay(500);
 for(let attempt=0;attempt<3;attempt++){
  observed=await nativeCall('observe');if(validThreadURL(observed.url))return observed;
  const direct=observed.nodes.find(node=>validThreadURL(node.href));if(direct){await nativeCall('browserAction',{action:'navigate',url:direct.href});await delay(500);continue}
  const open=observed.nodes.find(node=>/^open in messenger$/i.test(node.label));if(open){await nativeCall('browserAction',{action:'click',id:open.id,epoch:observed.epoch});await delay(500);continue}
  const details=observed.nodes.find(node=>/^(?:chat settings|conversation details)$/i.test(node.label));if(details){await nativeCall('browserAction',{action:'click',id:details.id,epoch:observed.epoch});await delay(350);continue}
  await delay(500);
 }
 throw Error('Temporary Facebook UI: seller conversation controls are unavailable.');
}
async function readConversations(job,r){
 if(r.view!=='Selling'){const w=workFor(r),p=conversationProgress(job,r),targets=new Set(job.targetCandidateKeys||[]),candidate=p.candidates.find(x=>job.leadURL&&sameThreadAddress(knownBuyingThread(w,x),job.leadURL))||p.candidates.find(x=>!targets.size||targets.has(inboxKey(x)));if(!candidate)throw Error('Temporary Facebook UI: the changed seller conversation is not visible yet.');const known=knownBuyingThread(w,candidate);await openBuyingThread(r,w,candidate);return browserAgent(job,'Read the already open seller conversation for '+r.name+'. Do not navigate and do not send. This Messenger URL was previously verified for '+candidate.person+' and this listing. Confirm that the visible banner contains both the exact seller and listing title. A banner link or Marketplace item ID is not required when those identities match the saved conversation. Return {"complete":true,"coverage":"current conversation checked","leads":[{"id":"seller name","url":"actual thread URL","last":"latest incoming seller message verbatim","unanswered":false,"state":"Interested or Negotiating or Pickup booked","offer":0,"offerQuote":"exact price quote","pickup":{"agreed":false,"cancelled":false,"price":0,"startsAt":"ISO timestamp with timezone","timeText":"exact time wording","location":"pickup location","ourQuote":"our agreement","theirQuote":"their agreement","priceQuote":"price agreement","timeQuote":"time agreement","locationQuote":"location agreement"}}]}. Distinguish our messages and system reminders from the seller. Set unanswered true only if no later outgoing response exists. Set pickup.agreed true when the full thread shows that one party proposed the price, time and location and the other party explicitly accepted or confirmed those details. The confirming message does not need to repeat every detail. Pickup still requires mutual agreement with no later cancellation. Do not invent dates. Current time: '+new Date().toString(),{history:true,maxSteps:2,validateResult:(result,evidence)=>{if(result.complete!==true||!Array.isArray(result.leads)||result.leads.length!==1)return 'Return one complete verified seller conversation.';return buyingThreadResultIssue({lead:result.leads[0]},evidence,r,candidate,known)}})}
 const p=conversationProgress(job,r);
 if(p.censusComplete&&p.censusVersion!==4)p.censusComplete=false;
 const inbox='https://www.facebook.com/marketplace/inbox?targetTab=SELLER';
 // Resume known unread threads before attempting another inbox census.
 const pendingReads=p.candidates.some(candidate=>!p.reads[inboxKey(candidate)]);
 if(!job.incremental&&!p.censusComplete&&!pendingReads){
  await discoverInboxCandidates(job,r,p,inbox);
 }
 const targetKeys=Array.isArray(job.targetCandidateKeys)?new Set(job.targetCandidateKeys):null,candidates=targetKeys?p.candidates.filter(candidate=>targetKeys.has(inboxKey(candidate))):p.candidates;if(targetKeys&&!candidates.length)throw Error('The changed buyer conversation is no longer visible. It will be checked again on the next inbox change.');let readThisRun=0,batchPaused=false;
 for(const candidate of candidates){
  const key=inboxKey(candidate);if(p.reads[key])continue;
  job.note='Reading buyer '+(Object.keys(p.reads).length+1)+' of '+p.candidates.length;saveSoon();
  await nativeCall('browserAction',{action:'navigate',url:inbox});
  const {result,evidence}=await browserAgent(job,'Read this one existing buyer conversation for my listing. Read only, send nothing. '+JSON.stringify({listing:r.name,listingURL:r.liveURL,buyer:candidate.person,inboxLabel:candidate.label})+'. Find its inbox button, scrolling if needed. Open the chat, then Chat settings > Open in Messenger for the actual thread URL. Confirm the listing banner points to the specified listing, not merely a similar title. Do not use Search Facebook. Ignore system reminders and quick-response suggestion panels when identifying the latest incoming buyer message. Suggested response buttons are not incoming messages. For an emoji or image-only message, use its exact observed accessible image description as last, without paraphrasing. If no message text or accessible description is observable, report that limitation instead of inventing a message. If history restoration or a PIN prompt blocks reading, stop for the user. Return {"lead":{"id":"buyer name","url":"actual /messages/t/ URL","last":"latest incoming buyer message verbatim","unanswered":true,"state":"Interested or Negotiating or Pickup booked","offer":0,"offerQuote":"exact price quote","pickup":{"agreed":false,"cancelled":false,"price":0,"startsAt":"ISO time with timezone","timeText":"visible time","location":"pickup location","ourQuote":"our agreement","theirQuote":"their agreement","priceQuote":"price agreement","timeQuote":"time agreement","locationQuote":"location agreement"}}}. Set unanswered true only if no later outgoing response exists. Pickup requires both parties to agree, with no later cancellation. Do not invent exact dates. Current time: '+new Date().toString(),{history:true,maxSteps:10,validateResult:(result,evidence)=>threadResultIssue(result,evidence,r)});
  const lead=result.lead,proof=evidence.find(o=>sameThreadAddress(o.url,lead?.url)&&typeof lead?.last==='string'&&lead.last.trim()&&o.text.includes(lead.last)&&(o.listings||[]).some(l=>marketplaceID(l.url)===marketplaceID(r.liveURL)));
  if(!validThreadURL(lead?.url)||!proof){const reason=!validThreadURL(lead?.url)?'invalid thread URL':!evidence.some(o=>sameThreadAddress(o.url,lead.url))?'thread URL does not match the observed page':!evidence.some(o=>sameThreadAddress(o.url,lead.url)&&typeof lead.last==='string'&&lead.last.trim()&&o.text.includes(lead.last))?'latest message is not present in the observed text':'listing banner does not match this inventory item';p.lastReadIssue={buyer:candidate.person,reason,returnedURL:lead?.url||'',returnedMessage:lead?.last||'',observedURLs:evidence.map(o=>o.url)};saveSoon();throw Error('Buyer conversation could not be matched to this listing: '+reason+'. Earlier verified reads are saved.');}
  lead.url=proof.url;
  delete p.lastReadIssue;
  p.reads[key]={lead,proof:{url:proof.url,text:compactConversationText(proof.text,lead.last),listings:(proof.listings||[]).slice(0,8)}};recordConversationLeads(r,[lead],[proof]);saveSoon();render();if(!job.incremental&&++readThisRun>=2&&p.candidates.some(x=>!p.reads[inboxKey(x)])){batchPaused=true;break}
 }
 const records=Object.values(p.reads),unique=[...new Map(records.map(x=>[x.lead.url,x.lead])).values()];
 return {result:{leads:unique,complete:job.incremental||p.censusComplete,incremental:!!job.incremental,continuation:batchPaused,censusVersion:4,coverage:(job.incremental?'Changed conversation checked.':p.coverage)+' '+unique.length+' verified buyer threads.'},evidence:records.map(x=>x.proof)};
}
if(typeof hydrate==='function'){const hydrateBeforeConversationTakeover=hydrate;hydrate=function(data){hydrateBeforeConversationTakeover(data);if((nativeState.sellingTakeoverVersion||0)<1){for(const r of rows.filter(r=>r.view==='Selling')){const w=workFor(r);if(laneEnabled.Selling&&w.enabled&&!w.importBaseline&&(w.leads||[]).some(lead=>lead.unanswered===true&&lead.last?.trim()&&lead.repliedTo!==lead.last))activateSellingReplies(r,{includeCurrent:true})}nativeState.sellingTakeoverVersion=1}}}
