// The agent judges comparability and value; code enforces owner limits and source provenance.
function resalePlan(r,result,evidence){
 if(!result||typeof result!=='object')throw Error('Research returned no recommendation.');
 const seen=new Set(),sources=(Array.isArray(result.sources)?result.sources:[]).filter(c=>{if(!c||!validListingURL(c.url)||seen.has(c.url)||!evidence.some(o=>o.url===c.url||(o.listings||[]).some(l=>l.url===c.url)))return false;seen.add(c.url);return true}).map(c=>({url:c.url,price:Number.isFinite(c.price)?c.price:null,reason:String(c.reason||''),limitations:String(c.limitations||'')}));
 if(result.needsHuman===true)throw Error(String(result.question||'Research needs your review.'));
 if(!sources.length)throw Error('Research needs at least one observed source.');
 if(!Number.isFinite(result.ask)||!Number.isFinite(result.minimum)||result.minimum<=0||result.ask<result.minimum||!String(result.rationale||'').trim())throw Error('Research returned an incomplete price recommendation.');
 const observedPrices=sources.map(x=>x.price).filter(x=>Number.isFinite(x)&&x>0).sort((a,b)=>a-b),reportedRange=[result.marketLow,result.marketHigh],marketRange=reportedRange.every(Number.isFinite)&&reportedRange[0]>0&&reportedRange[1]>=reportedRange[0]?reportedRange:(observedPrices.length?[observedPrices[0],observedPrices[observedPrices.length-1]]:null);
 const known=r.costKnown===true||(r.costKnown!==false&&r.offer>0),required=known?r.offer+(r.costs||0)+(r.profitTarget??minProfit):0;
 if(result.minimum<required)throw Error('Recommended minimum conflicts with your cost and profit target. Review the research.');
 return {ask:result.ask,minimum:result.minimum,marketLow:marketRange?.[0]??null,marketHigh:marketRange?.[1]??null,sources,rationale:String(result.rationale),uncertainties:Array.isArray(result.uncertainties)?result.uncertainties.map(String):[],strategy:r.pricingStrategy||'Balanced',checkedAt:new Date().toISOString(),basis:'Agent market estimate; advertised prices are not confirmed sales',costKnown:known};
}
async function researchResale(job,r){
 const record={id:crypto.randomUUID(),startedAt:new Date().toISOString(),status:'Researching',observations:[],steps:[],recommendation:null};r.researchHistory=[...(r.researchHistory||[]),record].slice(-3);r.inventoryNote='Researching market price';
 const capture=(o,step)=>{record.observations.push({url:o.url,text:compactStoredText(o.text,'',3000)});record.observations=record.observations.slice(-12);if(step){record.steps.push(compactStoredText(step,'',500));record.steps=record.steps.slice(-24)}saveSoon()};
 try{
 await nativeCall('browserAction',{action:'navigate',url:'https://www.facebook.com/marketplace/'});
 const facts={name:r.name,specifications:r.specifications||{},condition:r.condition,accessories:r.accessories||'',notes:r.detail,location:r.location,strategy:r.pricingStrategy||'Balanced',purchaseCost:r.costKnown===false?null:r.offer,profitTarget:r.profitTarget??minProfit};
 const {result,evidence}=await browserAgent(job,'Determine a reasonable local asking price and negotiation minimum for this item: '+JSON.stringify(facts)+'. Research current Marketplace evidence. Choose effective searches, shortlist promising comparisons, then inspect what matters. Use judgment about model variations, condition, accessories, and local market. Exact wording and a fixed number of comparisons are not requirements. Continue when another search could resolve uncertainty. Distinguish advertised prices from actual sold evidence. Do not claim sold prices without evidence. Estimate a defensible current market price range separately from the recommended list price and negotiation minimum. Recommend prices for the selected selling strategy; purchase cost does not determine market value. Distinguish owner-supplied facts from verified observations. Never call owner-supplied battery health independently verified. Explicitly list assumptions. Ask the owner only if missing facts materially prevent a useful recommendation. Read only, never contact or publish. Return {"marketLow":0,"marketHigh":0,"ask":0,"minimum":0,"rationale":"explain the valuation and adjustments","sources":[{"url":"observed listing URL","price":0,"reason":"why useful","limitations":"differences or uncertainty"}],"uncertainties":["remaining uncertainties"],"needsHuman":false,"question":""}. Return partial research and a specific question if blocked.',{capture,history:true,maxSteps:12});
 record.recommendation=result;const plan=resalePlan(r,result,evidence);if(r.liveURL&&plan.minimum>r.ask){r.pricing=plan;throw Error('Research minimum exceeds your live asking price. Review pricing before enabling negotiations.')}if(!r.liveURL)r.ask=plan.ask;r.minimum=Math.min(r.ask,plan.minimum);r.resale=plan.ask;r.pricing=plan;r.pricingFingerprint=typeof resaleFingerprint==='function'?resaleFingerprint(r):'';workFor(r).floor=r.minimum;record.status='Recommended';
 r.inventoryNote='Market estimate '+money(plan.ask)+' · Minimum '+money(plan.minimum)+'. '+(!r.liveURL&&!photos[r.photo]?'Add a real product photo.':'');addActivity(r.name+': resale price researched');if(r.liveURL){const w=workFor(r);resumeImportedManagement(r);w.next=w.enabled?'Managing buyer conversations':'Tracking listing';}else if(photos[r.photo]&&r.policy!=='store')queueJob('draft',r);
 }catch(e){record.status='Needs review';record.error=e.message;throw e}finally{record.finishedAt=new Date().toISOString();saveSoon()}
}
function openPriceResearch(r){
 settings=true;settingsTitle='Price research';const records=[...(r.researchHistory||[])].reverse();
 const report=x=>{const rec=x.recommendation;return (rec?'<div class="mp-money-grid"><div class="mp-money-stat"><span>Suggested ask</span><strong>'+money(rec.ask)+'</strong></div><div class="mp-money-stat"><span>Suggested minimum</span><strong>'+money(rec.minimum)+'</strong></div></div>':'')+(x.error?'<p>'+esc(x.error)+'</p>':'')+(rec?'<details><summary>Reasoning and assumptions</summary><p>'+esc(rec.rationale||'')+'</p><ul>'+(rec.uncertainties||[]).map(u=>'<li>'+esc(u)+'</li>').join('')+'</ul></details><h3>'+(rec.sources||[]).length+' comparisons</h3>'+(rec.sources||[]).map(c=>'<details><summary>'+money(c.price||0)+' · '+esc(c.reason||'Comparison')+'</summary><p>'+esc(c.limitations||'')+'</p><p>'+esc(c.url||'')+'</p></details>').join(''):'')+'<details><summary>Observed evidence · '+x.observations.length+' pages</summary>'+x.observations.map(o=>'<p>'+esc(o.url)+'</p><pre style="white-space:pre-wrap">'+esc(o.text)+'</pre>').join('')+'</details>'};
 $('#mp-settings').innerHTML='<h3>'+esc(r.name)+'</h3>'+(r.liveURL?'<p>Live asking price: '+money(r.ask)+'. Research does not change your Facebook price.</p>':'')+records.map((x,i)=>i?'<details class="mp-chart-panel"><summary>Earlier research · '+esc(x.status)+'</summary>'+report(x)+'</details>':'<article class="mp-chart-panel"><strong>'+esc(x.status)+'</strong>'+report(x)+'</article>').join('')+(!records.length?'<p>No research yet.</p>':'')+'<button id="research-back" class="mp-small-button">Back</button>';render();window.scrollTo(0,0);$('#research-back').onclick=()=>{settings=false;render()};
}
function decoratePricing(){
 if(!settings&&view==='Stock')rows.filter(r=>r.stockTracked&&r.researchHistory?.length).forEach(r=>{const card=$$('[data-stock-edit]').find(b=>+b.dataset.stockEdit===r.id)?.closest('.inv-card');if(card&&!card.querySelector('.research-open')){const b=document.createElement('button');b.className='mp-small-button research-open';b.textContent='Price research';b.onclick=()=>openPriceResearch(r);card.append(b)}});
 if(!settings&&view==='Stock')rows.filter(r=>r.stockTracked&&r.costKnown===false).forEach(r=>{const b=$$('[data-stock-edit]').find(b=>+b.dataset.stockEdit===r.id);const card=b?.closest('.inv-card');if(card&&!card.querySelector('.cost-unknown')){const t=document.createElement('small');t.className='cost-unknown';t.textContent='Purchase cost unknown';card.append(t)}});
 if(!settings||!$('#inv-edit')||$('#pricing-strategy'))return;
 const f=$('#inv-edit'),r=rows.find(x=>String(x.sku)===f.elements.sku.value);if(!r)return;
 const el=document.createElement('div');el.className='mp-fields';el.innerHTML='<label>Specifications<textarea id="item-specifications"></textarea></label><label>Included accessories<input id="item-accessories"></label><label>Selling strategy<select id="pricing-strategy">'+['Sell faster','Balanced','Maximize price'].map(x=>'<option>'+x+'</option>').join('')+'</select></label><label><input type="checkbox" id="pricing-cost-known"> Purchase cost known</label><button type="button" class="mp-small-button" id="pricing-research">Research selling price</button><p>Real photos required. Market prices are estimates.</p>'+ (r.pricing?'<p>'+esc(r.pricing.rationale||'')+'</p><p>'+esc((r.pricing.uncertainties||[]).join(' '))+'</p>':'')+'';f.prepend(el);$('#item-specifications').value=typeof r.specifications==='string'?r.specifications:JSON.stringify(r.specifications||{});$('#item-accessories').value=r.accessories||'';$('#pricing-strategy').value=r.pricingStrategy||'Balanced';$('#pricing-cost-known').checked=r.costKnown===true||(r.costKnown!==false&&r.offer>0);
 if(!$('#pricing-cost-known').checked)f.elements.offer.value='';f.elements.offer.required=false;
 $('#pricing-research').onclick=()=>{r.pricingStrategy=$('#pricing-strategy').value;queueJob('price',r);feedback('Price research queued. Follow Activity.');saveSoon()};
}
